// Doctor Report engine — doctor-ready portable summary.
//
// Builds a paste-friendly PLAIN-TEXT report of the last N days (default 30)
// from three local sources:
//   - Medications: MedsManager.all() records, with the scheduled-med
//     adherence % passed through from Analytics.getMedAdherence (REUSED —
//     adherence math is never re-derived here).
//   - Sleep: the `wellness_rest_log` localStorage key (RecoveryUI's store,
//     keyed YYYY-MM-DD).
//   - Activity & focus: History.getSessions() (IndexedDB session records).
//
// Contract:
//   - Strictly READ-ONLY. No writes to any store, no js/schema.js, no sync
//     modules, zero DOM. Delivery (copy / share / download) is Export's job
//     (copyText / shareText / downloadText).
//   - Descriptive-first copy: plain statements of logged data. No
//     interpretation, no advice, no medical language beyond the footer
//     disclaimer.
//   - Empty-state is the DEFAULT path: a missing engine (MedsManager /
//     Analytics / History may be undefined on partial pages) or an empty /
//     malformed store renders that section's "No X logged in this window."
//     line. Malformed rows are skipped, never thrown on; buildReport always
//     resolves — an all-empty device still gets a complete report.
//   - Pure per-section builders + window helpers live on `_internals` so
//     tests can clock-pin (fixed `now`) without IndexedDB or live singletons.

const DoctorReport = (() => {

  // Footer disclaimer — the report's ONLY non-descriptive sentence (brief
  // verbatim). Exposed on _internals so tests can assert the exact copy.
  const FOOTER = 'Generated by Tempo. Data as logged by the user — descriptive only, no medical interpretation.';

  const REST_LOG_KEY = 'wellness_rest_log';

  // ── Window + formatting helpers (pure) ──────────────────────────────

  // Last-N-local-calendar-days window including today, mirroring
  // Analytics.getMedAdherence's bounds so the report's dose counts and the
  // passed-through adherence % describe the same span:
  //   [startOfDay(now) - (days-1)d, startOfDay(now) + 1d)
  function computeWindow(days = 30, now = Date.now()) {
    const d = (typeof days === 'number' && isFinite(days) && days >= 1)
      ? Math.floor(days)
      : 30;
    const at = (typeof now === 'number' && isFinite(now)) ? now : Date.now();
    const today = new Date(at); today.setHours(0, 0, 0, 0);
    const startMs = new Date(today).setDate(today.getDate() - (d - 1));
    const endMs = today.getTime() + 86400000;
    return {
      days: d,
      startMs,
      endMs,
      startKey: Utils.localDateKey(new Date(startMs)),
      endKey: Utils.localDateKey(today),
      generatedKey: Utils.localDateKey(new Date(at)),
    };
  }

  // Normalize a caller-supplied opts bag (usually computeWindow output) to
  // safe bounds so the pure builders never throw on a partial fixture.
  function windowOf(opts) {
    const o = opts || {};
    return {
      startMs: (typeof o.startMs === 'number' && isFinite(o.startMs)) ? o.startMs : -Infinity,
      endMs: (typeof o.endMs === 'number' && isFinite(o.endMs)) ? o.endMs : Infinity,
      days: (typeof o.days === 'number' && isFinite(o.days) && o.days >= 1) ? Math.floor(o.days) : 30,
    };
  }

  // Deterministic "YYYY-MM-DD HH:MM" (local time). Locale-independent on
  // purpose — the report must paste identically everywhere, and tests
  // assert exact strings.
  function formatDateTime(ms) {
    const d = new Date(ms);
    const hh = String(d.getHours()).padStart(2, '0');
    const mm = String(d.getMinutes()).padStart(2, '0');
    return `${Utils.localDateKey(d)} ${hh}:${mm}`;
  }

  // "HH:MM" / "H:MM" 24h clock string → minutes since midnight, or null on
  // anything malformed (rest_log is a synced store — a foreign device could
  // have written garbage here).
  function clockToMinutes(str) {
    if (typeof str !== 'string') return null;
    const m = /^(\d{1,2}):(\d{2})$/.exec(str.trim());
    if (!m) return null;
    const h = Number(m[1]);
    const min = Number(m[2]);
    if (h > 23 || min > 59) return null;
    return h * 60 + min;
  }

  // ── Store parsers / filters (pure) ──────────────────────────────────

  // Parse the raw `wellness_rest_log` value into normalized day entries:
  //   [{ dateKey, dayStartMs, sleep|null, naps[] }] sorted ascending.
  // Defensive at every level (audit risk #3): null / non-JSON raw → [];
  // malformed day keys (bad shape OR calendar-invalid like 2026-13-05,
  // caught by the localDateKey round-trip) are skipped; non-object day
  // entries are skipped; naps are filtered to rows with a finite
  // non-negative durationMs. Accepts an already-parsed object too so test
  // fixtures don't have to stringify.
  function parseRestLog(raw) {
    let log = null;
    if (typeof raw === 'string' && raw) {
      try { log = JSON.parse(raw); } catch (e) { return []; }
    } else if (raw && typeof raw === 'object') {
      log = raw;
    }
    if (!log || typeof log !== 'object' || Array.isArray(log)) return [];

    const out = [];
    Object.keys(log).forEach(key => {
      if (!/^\d{4}-\d{2}-\d{2}$/.test(key)) return;
      const parts = key.split('-');
      const day = new Date(Number(parts[0]), Number(parts[1]) - 1, Number(parts[2]));
      const dayStartMs = day.getTime();
      // Round-trip check rejects calendar rollovers (month 13, Feb 30, …)
      // that the Date constructor would silently re-bucket.
      if (!isFinite(dayStartMs) || Utils.localDateKey(day) !== key) return;

      const entry = log[key];
      if (!entry || typeof entry !== 'object' || Array.isArray(entry)) return;
      const sleep = (entry.sleep && typeof entry.sleep === 'object' && !Array.isArray(entry.sleep))
        ? entry.sleep
        : null;
      const naps = Array.isArray(entry.naps)
        ? entry.naps.filter(n =>
            n && typeof n === 'object'
            && typeof n.durationMs === 'number'
            && isFinite(n.durationMs)
            && n.durationMs >= 0)
        : [];
      out.push({ dateKey: key, dayStartMs, sleep, naps });
    });
    out.sort((a, b) => a.dayStartMs - b.dayStartMs);
    return out;
  }

  // History sessions whose `date` lands inside [startMs, endMs). Rows with
  // a missing / unparseable date are skipped, never thrown on.
  function filterSessions(sessions, startMs, endMs) {
    return (Array.isArray(sessions) ? sessions : []).filter(s => {
      if (!s || typeof s !== 'object') return false;
      let t = NaN;
      try { t = new Date(s.date).getTime(); } catch (e) { return false; }
      if (!isFinite(t)) return false;
      return t >= startMs && t < endMs;
    });
  }

  // MedsManager.all() returns createMed() instances (getter methods), but
  // fixtures — and any future plain-record source — may hand us wire-format
  // objects. Normalize both to one plain shape; null on garbage so the
  // caller can filter(Boolean).
  function normalizeMed(med) {
    if (!med || typeof med !== 'object') return null;
    try {
      const pick = (getter, field) =>
        (typeof med[getter] === 'function') ? med[getter]() : med[field];
      const id = pick('getId', 'id');
      const name = pick('getName', 'name');
      const dose = pick('getDose', 'dose');
      const frequency = pick('getFrequency', 'frequency');
      const lastTakenAt = pick('getLastTakenAt', 'lastTakenAt');
      const doseLog = pick('getDoseLog', 'doseLog');
      return {
        id: (id === undefined) ? null : id,
        name: (typeof name === 'string' && name.trim()) ? name.trim() : 'Medication',
        dose: (typeof dose === 'string') ? dose.trim() : '',
        frequency: (typeof frequency === 'string' && frequency) ? frequency : 'as-needed',
        lastTakenAt: (typeof lastTakenAt === 'number' && isFinite(lastTakenAt)) ? lastTakenAt : null,
        doseLog: Array.isArray(doseLog)
          ? doseLog.filter(e => e && typeof e.takenAt === 'number' && isFinite(e.takenAt))
          : [],
      };
    } catch (e) { return null; }
  }

  // ── Section builders (pure — return one string block each) ──────────

  function buildHeader(opts) {
    const w = windowOf(opts);
    const o = opts || {};
    // Keys come from computeWindow in production; recompute defensively for
    // fixtures that only pass bounds.
    const startKey = typeof o.startKey === 'string' ? o.startKey : Utils.localDateKey(new Date(w.startMs));
    const endKey = typeof o.endKey === 'string' ? o.endKey : Utils.localDateKey(new Date(w.endMs - 1));
    const generatedKey = typeof o.generatedKey === 'string' ? o.generatedKey : endKey;
    return [
      'TEMPO HEALTH SUMMARY',
      `Last ${w.days} days (${startKey} to ${endKey})`,
      `Generated ${generatedKey}`,
    ].join('\n');
  }

  // Human labels for the V2 frequency enum. Unknown values (F20
  // forward-compat — a newer schema may mint e.g. 'three-times-daily')
  // render verbatim rather than being rewritten.
  function frequencyLabel(freq) {
    if (freq === 'once-daily') return 'once daily';
    if (freq === 'twice-daily') return 'twice daily';
    if (freq === 'as-needed') return 'as needed';
    return freq;
  }

  function countDosesInWindow(doseLog, startMs, endMs) {
    let count = 0;
    (Array.isArray(doseLog) ? doseLog : []).forEach(e => {
      if (!e || typeof e.takenAt !== 'number' || !isFinite(e.takenAt)) return;
      if (e.takenAt >= startMs && e.takenAt < endMs) count++;
    });
    return count;
  }

  // Last dose overall (not window-clipped — "last taken 45 days ago" is
  // exactly what a prescriber wants to see). lastTakenAt mirror preferred;
  // falls back to the doseLog tail when the mirror is absent.
  function lastDoseMs(med) {
    if (typeof med.lastTakenAt === 'number' && isFinite(med.lastTakenAt)) return med.lastTakenAt;
    let max = null;
    (Array.isArray(med.doseLog) ? med.doseLog : []).forEach(e => {
      if (!e || typeof e.takenAt !== 'number' || !isFinite(e.takenAt)) return;
      if (max === null || e.takenAt > max) max = e.takenAt;
    });
    return max;
  }

  // Per med: name, dose, frequency, doses-in-window, last taken. Scheduled
  // meds additionally show the adherence % passed through from
  // Analytics.getMedAdherence (matched by id, then name); as-needed meds
  // show counts only — no adherence concept. A scheduled med with no
  // matching adherence entry (Analytics absent / stubbed empty) simply
  // omits the line — we never invent a number.
  function buildMedsSection(meds, adherence, opts) {
    const w = windowOf(opts);
    const list = Array.isArray(meds) ? meds : [];
    const lines = ['MEDICATIONS'];
    if (list.length === 0) {
      lines.push('No medications logged in this window.');
      return lines.join('\n');
    }

    const byId = new Map();
    const byName = new Map();
    if (adherence && Array.isArray(adherence.meds)) {
      adherence.meds.forEach(a => {
        if (!a || typeof a !== 'object') return;
        if (a.id != null) byId.set(a.id, a);
        if (typeof a.name === 'string') byName.set(a.name, a);
      });
    }

    list.forEach(med => {
      if (!med || typeof med !== 'object') return;
      const dosePart = med.dose ? ` (${med.dose})` : '';
      lines.push(`- ${med.name}${dosePart} — ${frequencyLabel(med.frequency)}`);

      const inWindow = countDosesInWindow(med.doseLog, w.startMs, w.endMs);
      const last = lastDoseMs(med);
      const lastLabel = (last === null) ? 'never' : formatDateTime(last);
      lines.push(`  Doses in window: ${inWindow} · Last taken: ${lastLabel}`);

      if (med.frequency !== 'as-needed') {
        const a = (med.id != null && byId.get(med.id)) || byName.get(med.name) || null;
        if (a && typeof a.adherencePct === 'number' && isFinite(a.adherencePct)) {
          lines.push(`  Adherence: ${Math.round(a.adherencePct)}%`);
        }
      }
    });
    return lines.join('\n');
  }

  // Bedtime/wake range across the window. Bedtimes before noon sort as
  // after-midnight (23:30 → 00:45 is "later", not "earlier") so the range
  // reads earliest-habitual → latest-habitual; wake times order plainly.
  function timeRangePart(label, values, isBedtime) {
    const entries = [];
    (Array.isArray(values) ? values : []).forEach(v => {
      const mins = clockToMinutes(v);
      if (mins === null) return;
      const key = (isBedtime && mins < 720) ? mins + 1440 : mins;
      entries.push({ label: v.trim(), key });
    });
    if (entries.length === 0) return null;
    entries.sort((a, b) => a.key - b.key);
    const first = entries[0].label;
    const last = entries[entries.length - 1].label;
    return (first === last) ? `${label} ${first}` : `${label} ${first}–${last}`;
  }

  // Sleep coverage + averages + bedtime/wake range + naps. A day counts as
  // "logged" only when its sleep entry has finite hours (the shape
  // RecoveryUI guarantees — hours is the one required field); quality /
  // bedtime / wake aggregate only from those logged days. Naps count
  // independently, so a naps-only window still renders instead of claiming
  // nothing was logged.
  function buildSleepSection(entries, opts) {
    const w = windowOf(opts);
    const lines = ['SLEEP'];
    const inWindow = (Array.isArray(entries) ? entries : []).filter(e =>
      e && typeof e.dayStartMs === 'number'
      && e.dayStartMs >= w.startMs && e.dayStartMs < w.endMs);

    let sleepDays = 0;
    let hoursSum = 0;
    let qualitySum = 0;
    let qualityCount = 0;
    const bedtimes = [];
    const wakes = [];
    let napCount = 0;
    let napMs = 0;

    inWindow.forEach(e => {
      const s = e.sleep;
      if (s && typeof s.hours === 'number' && isFinite(s.hours)) {
        sleepDays++;
        hoursSum += s.hours;
        if (typeof s.quality === 'number' && isFinite(s.quality)) {
          qualitySum += s.quality;
          qualityCount++;
        }
        if (clockToMinutes(s.bedtime) !== null) bedtimes.push(s.bedtime);
        if (clockToMinutes(s.wakeTime) !== null) wakes.push(s.wakeTime);
      }
      (Array.isArray(e.naps) ? e.naps : []).forEach(n => {
        napCount++;
        napMs += n.durationMs;
      });
    });

    if (sleepDays === 0 && napCount === 0) {
      lines.push('No sleep logged in this window.');
      return lines.join('\n');
    }

    lines.push(`Sleep logged ${sleepDays} of ${w.days} days`);
    if (sleepDays > 0) {
      let avgLine = `Average: ${(hoursSum / sleepDays).toFixed(1)} hr`;
      if (qualityCount > 0) avgLine += ` · quality ${(qualitySum / qualityCount).toFixed(1)}/5`;
      lines.push(avgLine);
    }
    const parts = [];
    const b = timeRangePart('Bedtime', bedtimes, true);
    if (b) parts.push(b);
    const wk = timeRangePart('Wake', wakes, false);
    if (wk) parts.push(wk);
    if (parts.length > 0) lines.push(parts.join(' · '));
    if (napCount > 0) {
      lines.push(`Naps: ${napCount} (total ${Utils.formatHuman(napMs)})`);
    }
    return lines.join('\n');
  }

  // Activity & focus over ALREADY window-filtered sessions (buildReport
  // runs filterSessions first). Cooking is excluded entirely — from the
  // counts AND from the section's emptiness test, so a cooking-only window
  // renders the empty-state line. Zero counts on the metric lines are
  // honest descriptions, not empty states, when any other session exists.
  function buildActivitySection(sessions) {
    const lines = ['ACTIVITY & FOCUS'];
    const list = (Array.isArray(sessions) ? sessions : [])
      .filter(s => s && typeof s === 'object' && s.type !== 'cooking');
    if (list.length === 0) {
      lines.push('No sessions logged in this window.');
      return lines.join('\n');
    }

    let focusMs = 0;
    let focusCount = 0;
    let mindfulCount = 0;
    let exerciseCount = 0;
    list.forEach(s => {
      if (s.type === 'flow' || s.type === 'pomodoro') {
        focusCount++;
        if (typeof s.duration === 'number' && isFinite(s.duration)) focusMs += s.duration;
      }
      if (Array.isArray(s.tags) && s.tags.includes('mindful')) mindfulCount++;
      if (s.type === 'interval') exerciseCount++;
    });

    if (focusCount > 0) {
      const plural = focusCount === 1 ? 'session' : 'sessions';
      lines.push(`Focus time (Flow + Pomodoro): ${Utils.formatHuman(focusMs)} across ${focusCount} ${plural}`);
    } else {
      lines.push('Focus sessions: 0');
    }
    lines.push(`Mindful sessions: ${mindfulCount}`);
    lines.push(`Exercise sessions: ${exerciseCount}`);
    return lines.join('\n');
  }

  // ── Public entry point ──────────────────────────────────────────────

  // Assemble the full report. Every store access is individually guarded —
  // a missing engine, a rejecting IDB read, or a corrupt localStorage value
  // degrades that section to its empty-state line; the promise always
  // resolves with a complete Header / Medications / Sleep / Activity /
  // Footer document.
  async function buildReport({ days = 30, now = Date.now() } = {}) {
    const win = computeWindow(days, now);

    let meds = [];
    try {
      if (typeof MedsManager !== 'undefined' && typeof MedsManager.all === 'function') {
        meds = MedsManager.all().map(normalizeMed).filter(Boolean);
      }
    } catch (e) { meds = []; }

    // Adherence pass-through. getMedAdherence windows off the live clock
    // internally — acceptable drift only when a caller pins a historical
    // `now`, which production never does (tests stub Analytics instead).
    let adherence = null;
    try {
      if (typeof Analytics !== 'undefined' && typeof Analytics.getMedAdherence === 'function') {
        adherence = await Analytics.getMedAdherence(win.days);
      }
    } catch (e) { adherence = null; }

    let restEntries = [];
    try {
      restEntries = parseRestLog(localStorage.getItem(REST_LOG_KEY));
    } catch (e) { restEntries = []; }

    let sessions = [];
    try {
      if (typeof History !== 'undefined' && typeof History.getSessions === 'function') {
        sessions = await History.getSessions();
      }
    } catch (e) { sessions = []; }
    const inWindowSessions = filterSessions(sessions, win.startMs, win.endMs);

    return [
      buildHeader(win),
      buildMedsSection(meds, adherence, win),
      buildSleepSection(restEntries, win),
      buildActivitySection(inWindowSessions),
      FOOTER,
    ].join('\n\n');
  }

  return {
    buildReport,
    _internals: {
      FOOTER,
      computeWindow,
      windowOf,
      formatDateTime,
      clockToMinutes,
      parseRestLog,
      filterSessions,
      normalizeMed,
      buildHeader,
      frequencyLabel,
      countDosesInWindow,
      lastDoseMs,
      buildMedsSection,
      timeRangePart,
      buildSleepSection,
      buildActivitySection,
    },
  };
})();
